export const SEARCH_INPUT = 'SEARCH_INPUT';
export const SEARCH_CLICK = 'SEARCH_CLICK';
export const SEARCH_RECIEVE = 'SEARCH_RECIEVE';

export const EDIT_INPUT = 'EDIT_INPUT';
export const EDIT_RECIEVE = 'EDIT_RECIEVE';

export const BOOK_FETCH = 'BOOK_FETCH';
export const BOOK_RECIEVE = 'BOOK_RECIEVE';
export const BOOK_REGISTER = 'BOOK_REGISTER';
export const BOOK_UN_REGISTER = 'BOOK_UN_REGISTER';

export const SERIES_INPUT = 'SERIES_INPUT';
export const SERIES_CLICK = 'SERIES_CLICK';
export const SERIES_FETCH = 'SERIES_FETCH';
export const SERIES_RECIEVE = 'SERIES_RECIEVE';
export const SERIES_REGISTER = 'SERIES_REGISTER';
export const SERIES_UN_REGISTER = 'SERIES_UN_REGISTER';

export const SERIES_TOGGLE = 'SERIES_TOGGLE';
export const SERIES_EDIT_CLICK = 'SERIES_EDIT_CLICK';
export const SERIES_EDIT_INPUT = 'SERIES_EDIT_INPUT';
